### ISSUE TITLE
implement the new version of gubbins - that can be sed fixed

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/ALPPACA#109]
Update to gubbins >= Gubbins commit id with fix is [9a1e55] 

Background: I had asked to provide a solution in gubbins to fix the seed - so it can be used for reproducibilitiy and validation purposes. This is now implemented in gubbins. 
Note: This should allows to have the pipeline core genome track more reproducible (still need to find if parsnp is deterministic).
Would allow better testing with IRIDA-ALPPACA version
 
Issue in gubbins requesting fix was : https://github.com/nickjcroucher/gubbins/issues/388

**Comment by hkaspersen** [comment]
Awaiting the image update on quay.io for this!

**Comment by evezeyl** [comment]
- [ ] we need to find out who do the images and ask if they can do
