### ISSUE TITLE
some options that would be great to have

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/ALPPACA#11]
Hi, 
Could you eventually make optional options where you could capture the boostrap files 

- wbtl  option | Like -wbt but bootstrap trees written with branch lengths. DEFAULT: OFF 
which captures boostraps with branch lengths into a `.ufboot` file 
[see here:](http://www.iqtree.org/doc/Command-Reference#Ultrafast bootstrap parameters) 

That would be nice eg if we want to use tipdating (with increased precision to account for uncertainties in the tree ie with Bactdating) or some other trials

Also might
Would be nice to have the xxx.phy.splits.nex file 
> support values in percentage for all splits (bipartitions), computed as the occurence frequencies in the bootstrap trees. This file can be viewed with the program SplitsTree to explore the conflicting signals in the data. So it is more informative than consensus tree osv 
That could allow us to understand a bit better trees when no clear answer
[see](http://www.iqtree.org/doc/Tutorial#assessing-branch-supports-with-ultrafast-bootstrap-approximation#Assessing branch supports with ultrafast bootstrap approximation)

Not sure if those options are in the version you are using in alppaca.
But upon update ... :D

**Comment by hkaspersen** [comment]
Added in v1.0.0
