### ISSUE TITLE
Automated tests: There are no automated tests to verify the functionality of the software. I understand that the pipeline requires an HPC to run the full pipeline, but automated tests could be made possible by unit testing the individual modules and/or integration testing on a subset of the original data.

### ISSUE THREAD

**Issue by hkaspersen** [NorwegianVeterinaryInstitute/ALPPACA#35]
Part of ALPPACA review: https://github.com/openjournals/joss-reviews/issues/4677

**Comment by hkaspersen** [comment]
Comment on how to implement testing:
https://github.com/openjournals/joss-reviews/issues/4677#issuecomment-1272026591
In NF-CORE pipelines, testing is implemented using a `test.config` file that defines the input and parameters of the test. 
However, as far as I can see, I don't understand fully how Nextflow handles a link to files online, and converts it to a channel.
Example from the [viralrecon](https://github.com/nf-core/viralrecon/blob/master/conf/test.config) pipeline:
```
// Input data to test amplicon analysis
    input              = 'https://raw.githubusercontent.com/nf-core/test-datasets/viralrecon/samplesheet/samplesheet_test_illumina_amplicon.csv'
    platform           = 'illumina'
    protocol           = 'amplicon'
```
here they use a samplesheet, and they have some nextflow processes that handle this, but I cannot see where it is converted to a channel for the processes after.
@evezeyl if you can look further into this i'd be grateful! Added @karinlag too in case you have any additional insight here.

**Comment by evezeyl** [comment]
As far as I can see in their pipeline they create the Chanel from the params.input which is the paths for a CSV file

In the test config you provide the path ... Just that it's online.

**Comment by hkaspersen** [comment]
Not yet managed to get the csv-file split into fasta channels. Asked on Nextflow Discussion:
https://github.com/nextflow-io/nextflow/discussions/3294

**Comment by hkaspersen** [comment]
The solution was to use the following:
```
fasta_channel = Channel
    .fromPath(params.input)
    .splitCsv(header:true, sep:",")
    .map { file(it.path) }
    .collect()
```
This will pull the fasta files and create one channel for all of them together

**Comment by hkaspersen** [comment]
Test (core genome) now functional

**Comment by hkaspersen** [comment]
Made test automatic when pushing to the dev branch. Check test before merging with master!
