### ISSUE TITLE
integrate cgMLST typing

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/ALPPACA#42]
Notes from discussion yesterday

Hi Håkon yes we can add chewbacca cgMLST typing and tree reconstruction

- I made public the cgMLST post analysis pipeline that I have functioning locally (rainy sunday project) <https://github.com/NorwegianVeterinaryInstitute/cgMLST_tree> . We we can start merging the pipelines when ready

- we need to think how we integrate chewbacca typing: eg how to make the cgMLST databases so they can be kept up to date, and for the different pathogens (user install locally and specify db ?, sync option with Chewie-NS ?) and how to make it as much user friendly has possible. We have to keep KISS for the users 

One condition for the integration : I need to learn what you learned during the joss paper submission (so guidance) !

**Comment by hkaspersen** [comment]
This work is part of the OEIO project issue:
https://github.com/NorwegianVeterinaryInstitute/ost_er_ikke_ost/issues/24

Add MLST as well for CC determinaton?

**Comment by hkaspersen** [comment]
Docker image:
3.1.0--pyhdfd78af_0

**Comment by hkaspersen** [comment]
mlst docker image:
2.23.0--hdfd78af_1

**Comment by hkaspersen** [comment]
- Add prepScheme process, with PTF input and scheme
- Output the scheme after
- AlleleCall process - output missing loci optionally in output dir
- Analysis: distances (output matrix), concatenating reports
- Report: Main statistics of alleles (boxplots?), clustering (NJ or singleLinkage), dendrogram from distances

**Comment by hkaspersen** [comment]
For CI test: find genes in input genomes with annotations

**Comment by hkaspersen** [comment]
Added in version 2.2.0
