### ISSUE TITLE
Minor comment on the structure of the JOSS submission

### ISSUE THREAD

**Issue by rcannood** [NorwegianVeterinaryInstitute/ALPPACA#45]
This is a minor comment as part of my review of your JOSS submission (https://github.com/openjournals/joss-reviews/issues/4677).

I believe the first two sections of the paper as they are currently formulated are labelled wrong. What I mean to say is, what is currently labelled as the Statement of Need in the paper is actually a summary of ALPPACA and the State of the field, whereas the Summary is actually a statement of need.

Currently:

> ### Summary
> Phylogenetic analysis is frequently used to unravel outbreaks and track the origins of pathogens worldwide. Phylogenetic analysis has also become commonplace in several research projects and clinical investigations, where time is often of the essence. This kind of analysis often entails running several tools consecutively, and many assumptions are made for the data used in each tool. To add to this complexity, several tools have been developed for each step in such an analysis, and sifting through these tools as a user may be time-consuming. Additionally, choosing a combination of compatible software for various analysis scenarios may require in-depth knowledge and experience in the field of microbial evolution, which often prevents non-specialists from utilizing such analyses. Here we present a solution that will help alleviate these problems in hopes of making it easier and faster to run reproducible phylogenetic analyses.
> 
> ### Statement of need
> A tooL for Prokaryotic Phylogeny And Clustering Analysis (ALPPACA) is a pipeline that allows both de-novo and reference-based phylogenetic analysis of prokaryotic genomes. The pipeline provides a suite of analyses tailored for different scenarios, designed to allow analysis of datasets represented by three different genetic diversity levels, all in one package. These levels of similarity influence what assumptions are used to consider sequences as orthologous when reconstructing the multiple alignment required for phylogenetic inference. By selecting an appropriate track for the data at hand, the user can be confident that these assumptions are taken care of within the framework of ALPPACA. The ability to run different datasets through different tracks within the same framework makes ALPPACA unique compared to other phylogeny pipelines such as Bactmap (https://nf-co.re/bactmap) and SNVPhyl (https://github.com/DHQP/SNVPhyl_Nextflow), where only mapping-based phylogeny is possible. Several research projects have provided the developmental platform of ALPPACA, and peer-reviewed papers have been published using this framework for phylogenetic analysis [@Kaspersen:2020;@Franklin-Alming:2021;@Smistad:2022;@Kravik:2022].

My interpretation of these sections are:

> ### Statement of need
> Phylogenetic analysis is frequently used to unravel outbreaks and track the origins of pathogens worldwide. Phylogenetic analysis has also become commonplace in several research projects and clinical investigations, where time is often of the essence. This kind of analysis often entails running several tools consecutively, and many assumptions are made for the data used in each tool. To add to this complexity, several tools have been developed for each step in such an analysis, and sifting through these tools as a user may be time-consuming. Additionally, choosing a combination of compatible software for various analysis scenarios may require in-depth knowledge and experience in the field of microbial evolution, which often prevents non-specialists from utilizing such analyses. 
> 
> ### Prokaryotic Phylogeny And Clustering Analysis
> A tooL for Prokaryotic Phylogeny And Clustering Analysis (ALPPACA) is a pipeline that allows both de-novo and reference-based phylogenetic analysis of prokaryotic genomes. The pipeline provides a suite of analyses tailored for different scenarios, designed to allow analysis of datasets represented by three different genetic diversity levels, all in one package. These levels of similarity influence what assumptions are used to consider sequences as orthologous when reconstructing the multiple alignment required for phylogenetic inference. By selecting an appropriate track for the data at hand, the user can be confident that these assumptions are taken care of within the framework of ALPPACA. 
>
> ### State of the field
> The ability to run different datasets through different tracks within the same framework makes ALPPACA unique compared to other phylogeny pipelines such as Bactmap (https://nf-co.re/bactmap) and SNVPhyl (https://github.com/DHQP/SNVPhyl_Nextflow), where only mapping-based phylogeny is possible. Several research projects have provided the developmental platform of ALPPACA, and peer-reviewed papers have been published using this framework for phylogenetic analysis [@Kaspersen:2020;@Franklin-Alming:2021;@Smistad:2022;@Kravik:2022].

However, if you would restructure the manuscript as suggested above, you don't have a summary section anymore, so further tweaking is necessary to solve this.

WDYT?

**Comment by hkaspersen** [comment]
Thank you for your feedback @rcannood! Yes, I agree with your interpretation when reading it again. I will restructure the manuscript and add a small summary section at the start. I think I got a bit confused about the summary section due to the [example manuscript](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography) that JOSS provide.

**Comment by hkaspersen** [comment]
@rcannood reading it yet again made me think - perhaps the "Prokaryotic Phylogeny and Clustering Analysis" section can actually work as the summary? Moving it up makes sense, as it is supposed to provide a "high level description of the functionality of the software", which it does. I am very close to the word limit, so I'm a bit reluctant to add a while new section.

**Comment by hkaspersen** [comment]
@evezeyl any thought on this?

**Comment by rcannood** [comment]
> @rcannood reading it yet again made me think - perhaps the "Prokaryotic Phylogeny and Clustering Analysis" section can actually work as the summary? Moving it up makes sense, as it is supposed to provide a "high level description of the functionality of the software", which it does. I am very close to the word limit, so I'm a bit reluctant to add a while new section.

Makes sense to me, swapping the two paragraphs seems to work quite nicely :)

**Comment by hkaspersen** [comment]
@rcannood See if you like the new structure better! :)

**Comment by rcannood** [comment]
:+1: looks good to me!

**Comment by evezeyl** [comment]
@hkaspersen I had a look, this was a great suggestion to reorganize as such. Its all good for me :)
