### ISSUE TITLE
sample sheet not checked for missing files

### ISSUE THREAD

**Issue by solveigmo** [NorwegianVeterinaryInstitute/ALPPACA#65]
If sample sheet is created before moving the reference to a sub-directory, one sample will be "missing" from the sample sheet. The pipeline runs without error or warning.

**Comment by hkaspersen** [comment]
File input currently not checked for functional paths due to nextflow not automatically checking these. Asked a question on nextflow discussions about this https://github.com/nextflow-io/nextflow/discussions/3444
