### ISSUE TITLE
latest image chewbbaca

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/ALPPACA#92]
Hi adding here (as notes )

Just scanning trough because I need to launch analyses ... so noting here what I think can be interesting

## To do 
- if not latest image with chewbbaca -> Eve must do new image docker image (with latest version)

## AlleleCall module
--force-continue   -> to bypass the  yes prompt
--cpu, --cpu-cores  **default is 1 ! **

New options that I had not seen before
-- option update profiles:  update new database (before was default)  - was it in allele call module or scheme creation?
--output-unclassified (will be nice for differences) -> so default as null but add the option
--output-missing

## we could consider adding that in ALPPACA  (as later enhancement ?) 
But not for OEIO we do not need (load and sync schema) 
- Chewie-NS[](https://chewbbaca.readthedocs.io/en/latest/user/modules/LoadSchema.html#loadschema-upload-a-schema-to-chewie-ns)

options to download, sync schema available 

## Other interesting options 
- https://chewbbaca.readthedocs.io/en/latest/user/modules/JoinProfiles.html

**Comment by evezeyl** [comment]
Eve check 
- [ ]  where did I see that  --update_schema command ?
- [ ] Håkon suggest considering : 
- - [ ]  Adding : [schema evaluatorl](https://l.workplace.com/l.php?u=https%3A%2F%2Fchewbbaca.readthedocs.io%2Fen%2Flatest%2Fuser%2Fmodules%2FSchemaEvaluator.html&h=AT2KnQfzlh-1RNJ_eKucdsDO1rf355Mhk8FKvoizUWOcBcg_FIQNyjK1zAXbLhYwa1KcmPai3u75sOAe65xOx3Cn53cQRR9PQ4CT9gxr-hNW-558O8lEWHkulIUSUMTNWmf1xn8WxvJVGuaV3xjFFvIuDA)
- - [ ] using instead of a local scheme: https://chewbbaca.readthedocs.io/en/latest/user/modules/DownloadSchema.html

-- [ ] Chewie .... can it comply with "gold standard of typing" ie profficiency test type (not curated scheme, bsr osv)

- [ ] Problem : should also make it possible for users to supply their own scheme... 
- [ ] Problem :  consider how to deal which change of changes

**Comment by evezeyl** [comment]
Eve check 
- [ ]  where did I see that  --update_schema command ?
- [ ] Håkon suggest considering : 
- - [ ]  Adding : [schema evaluatorl](https://l.workplace.com/l.php?u=https%3A%2F%2Fchewbbaca.readthedocs.io%2Fen%2Flatest%2Fuser%2Fmodules%2FSchemaEvaluator.html&h=AT2KnQfzlh-1RNJ_eKucdsDO1rf355Mhk8FKvoizUWOcBcg_FIQNyjK1zAXbLhYwa1KcmPai3u75sOAe65xOx3Cn53cQRR9PQ4CT9gxr-hNW-558O8lEWHkulIUSUMTNWmf1xn8WxvJVGuaV3xjFFvIuDA)
- - [ ] using instead of a local scheme: https://chewbbaca.readthedocs.io/en/latest/user/modules/DownloadSchema.html

-- [ ] Chewie .... can it comply with "gold standard of typing" ie profficiency test type (not curated scheme, bsr osv)

- [ ] Problem : should also make it possible for users to supply their own scheme... 
- [ ] Problem :  consider how to deal which change of changes

**Comment by hkaspersen** [comment]
Added in version 2.2.0
